### PR TITLE
Added some parameters for posts

### PR DESCRIPTION
**Pull request by emitor**
Hi @budparr,  while I was customizing your theme for my blog I've added some parameters to the posts that might be useful for others. I'm really new with Hugo and I'm not sure if it's correct what I did but It works and I'm open to learn and the critics.

I would be very happy to keep sharing the changes that are useful for me or other things that you may need.

Regards!

### CODE REVIEW

**Comment by budparr** [comment]
Hi @emitor Thank you. I like this idea. Give me a bit of time to go through the changes thoroughly and I will likely merge, though there's a conflict right now.

Wondering why you switched from using `.Site.Params` to `$.Param`?

**Comment by emitor** [comment]
I'm happy that you liked the changes!

I'm not sure why I've changed `.Site.Params` to `$.Param` I think that for the file single.html I've copied and pasted from the line 49 of the file /layouts/_default/baseof.html.
      
I've tried to fix the conflict here but it's still wrong. I'm doing the changes on my computer and do the commits right now. I've also added some other parameters, I'm not sure if I can add it in this Pull request or should I create another.

**Comment by emitor** [comment]
Ok, It seems that It add them automatically, sorry for my ignorance, I'm new in this. Please check them now.

If you want me to do some refactoring let me know. Maybe the parameters names are not so good for you.

**Comment by regisphilibert** [comment]
Thanks @emitor for the work done here!

I'm sorry this PR has lingered for this long but nonetheless its history broad impact is a now bit much for us to review and safely merge. Would you mind creating an issue (or issues) listing the purpose/feature of this PR so we can track, spec, and potentially add them to a later version through several PRs. We're in the process of giving some much deserved love to Ananke in 2020.

I'm closing this one.

**Pull request closed without merging**
