### PR TITLE
Update site-footer.html

### PR DESCRIPTION
**Pull request by jorgeml**
Change footer to allow changing the copyright as a site parameter.

I'm not an HTML expert so I'm not sure about the formatting.

### CODE REVIEW

**Comment by budparr** [comment]
Thank you for this. I think we should use Hugo's built in Site Config value and use Hugo's default function instead of `else`. For example:
```
{{ with .Site.Copyright | default "&copy;" }} {{ . | safeHTML }} {{ now.Format "2006"}} {{ end }}
```

**Comment by jorgeml** [comment]
> Thank you for this. I think we should use Hugo's built in Site Config value and use Hugo's default function instead of `else`. For example:
> 
> ```
> {{ with .Site.Copyright | default "&copy;" }} {{ . | safeHTML }} {{ now.Format "2006"}} {{ end }}
> ```

Fine by me, I'm far from being a Hugo expert and if that works...

**Comment by budparr** [comment]
Do you want to make the change in your PR, or shall I do it myself?

**Comment by jorgeml** [comment]
Would you mind doing the change yourself please? I don't want to break anything.

**Comment by budparr** [comment]
No problem at all. Thanks for bringing it up.

**Pull request closed without merging**
