### PR TITLE
RSS svg icon

### LINKED ISSUE #278: RSS svg icon
I love this theme, thank you!

Would it be possible to get an RSS svg icon? I would like one next to my Twitter icon! I see there are 13 social rss icons and I'm thinking having an RSS icon is something a lot of people might want..

Thanks again,  Nick

### PR DESCRIPTION
**Pull request by mountainbug95**
Fixes #278

### CODE REVIEW

**Comment by regisphilibert** [comment]
@mountainbug95 this js file has been processed differently, any idea why?

**Comment by mountainbug95** [comment]
@regisphilibert I'm not quite sure why it is different. I had to redeploy the assets to get my added class for the rss icon to work. I'm sure that's what caused it.

**Comment by regisphilibert** [comment]
As the asset fingerpint is unchanged we don't need this file to be committed though. Any chance we can have it removed from the PR?

**Comment by mountainbug95** [comment]
sure thing

**Pull request merged**
